name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.x.x
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm fmt:check
      - run: pnpm build
